# Dockerfile
FROM apache/airflow:3.0.3

# Copy your requirements.txt into the image
COPY requirements.txt /tmp/requirements.txt

# Install the Python dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt
