services:
  # MLflow Tracking Server
  mlflow:
    image: python:3.11-slim
    container_name: mlflow-server
    command: >
      bash -c "
        pip install mlflow boto3 psycopg2-binary &&
        mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root s3://amt-dansarpong-mlops/artifacts --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      "
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
    depends_on:
      - postgres
    networks:
      - mlops-network

  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres-mlflow
    environment:
      - POSTGRES_DB=mlflow
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mlops-network

volumes:
  postgres_data:

networks:
  mlops-network:
    driver: bridge
