name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  REPO: dansarpong/mlops-capstone
  AWS_REGION: us-east-1
  S3_BUCKET: mlops-dev-dansarpong-s3
  SHARED_VENV_PATH: venv

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run deployment on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clone the repository
          sudo rm -rf mlops-capstone || true
          git clone https://github.com/${{ env.REPO }} mlops-capstone
          cd mlops-capstone

          # Download env file from S3
          aws s3 cp s3://${{ env.S3_BUCKET }}/.env .env

          # Set up shared python environment
          if [ ! -d "${{ env.SHARED_VENV_PATH }}" ]; then
            python3.12 -m venv ${{ env.SHARED_VENV_PATH }}
          fi
          source ${{ env.SHARED_VENV_PATH }}/bin/activate

          # Install dependencies if requirements.txt was modified
          if git diff --name-only HEAD^ HEAD | grep -q 'requirements.txt'; then
            pip install --no-cache-dir -r requirements.txt --cache-dir /var/tmp/.cache
          fi

          # Stop existing Docker containers
          docker-compose -f docker-compose.yml down || true

          # Start Docker containers
          docker-compose -f docker-compose.yml up -d --build

  cleanup:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Cleanup old Docker images
      run: |
        docker image prune -f